### ISSUE TITLE
Most accurate formula for "realFeel"? 

### ISSUE THREAD

**Issue by demian85** [strikeentco/feels#3]
Hi, thanks for creating this module. It's really useful for my IoT project.

I was wondering which is the most accurate formula used to calculate the real feel like any other weather service would do.
I'm currently using AAT, since it makes sense to me. Humidex is too high.
But, I was trying to find a formula that takes into account not only the wind speed (no wind inside my bedroom for now :P), but the pressure in hPa, since I read it is quite relevant for calculating the dew point and everything is related.

Any thoughts? Thanks!

**Comment by strikeentco** [comment]
Hello! It's nice to hear that this module is useful for you.

> I was wondering which is the most accurate formula used to calculate the real feel like any other weather service would do.

It was for this purpose that this module was created.

You can simply use method `.like()`, and you will get real feel based on 4 formulas (by default):
- Heat index
- Humidex
- Australian apparent temperature
- Wind chill

Just pass all the data you have and `Feels.like` will do its best.

Some of this formulas is using Water Vapour Pressure (WVP), which can be calculated by temperature and humidity or by dew point. But you don't need to do it by yourself, `feels` will do it for you, using provided data.

`feels` will automatically calculate all data that it needs using all data you passed: temperature, wind speed, humidity, dew point and Water vapour pressure.

Dew point and water vapour pressure will be calculated using temperature and humidity.

Humidity will be calculated using temperature and dew point or using temperature and  water vapour pressure.

```js
const Feels = require('feels');

new Feels({
  temp: 20,
  humidity: 75,
}).like(); // -> ~23.4

new Feels({
  temp: 20,
  dewPoint: 15
}).like(); // -> ~23.4
```

**Comment by demian85** [comment]
Sorry, but it's still not clear to me. The following is giving me two different outputs for the same inputs:

```javascript
const Feels = require('feels');

const temp = 22;
const humidity = 85;

const config = {
  temp,
  humidity,
  speed: 0
};

const realFeel = new Feels(config).like();
const realFeel2 = Feels.AAT(temp, 0, humidity);

console.log(realFeel, realFeel2); /// 26.26533965315363 25.395874301328607
```

`realFeel2` seems more accurate to me (for my use case), but still, there is no formula that takes the air pressure into account (hPa). I'm assuming that's not the same as water vapor pressure.

**Comment by strikeentco** [comment]
In your case, `.like()` calculates real feel using Heat Index + Humidex + AAT:
```js
const Feels = require('feels');

const temp = 22;
const humidity = 85;

const config = {
  temp,
  humidity,
  speed: 0
};

const realFeel = new Feels(config).like();
const realFeel2 = Feels.AAT(temp, 0, humidity);
const realFeel3 = (Feels.heatIndex(temp, humidity) + Feels.humidex(temp, humidity) + Feels.AAT(temp, 0, humidity)) / 3;

console.log(realFeel, realFeel2); /// 26.26533965315363 25.395874301328607
console.log(realFeel === realFeel3); /// 26.26533965315363
```

Water vapour pressure is measured in hPa, and calculates using temperature and humidity or using dew point:
https://github.com/strikeentco/feels/blob/98e38d1e9af3babf75eee9df80d292a61beae8e7/lib/base.js#L97

Using multiple formulas give more accurate real feel because they are using different constants and initial values.

Real feel is apparent temperature and can't be really accurate :)

**Comment by strikeentco** [comment]
Each formula has its own limits, and was designed for specific geographical and meteorological conditions.

AAT is Australian formula, Humidex is Canadian, etc.

The heat index is used for temperatures more than 20 Celsius.
The AWBGT is used for temperatures more than 15 Celsius.
The humidex is used for temperatures more than 0 Celsius.
The wind chill is used for temperatures less than 0 Celsius.

When you use `.like()` method it will determine which formulas are appropriate for the current values and will use only them.

Yeah, you can use only AAT formula with temperature and humidity and water vapour pressure will be calculated from provided values.

But I recommend to you use `.like()` method with as much numbers of formulas as possible. Because eventually it will be more precise than index from only one formula.

**Comment by demian85** [comment]
Understood, but still, atmospheric pressure is not taken into account, is that okay? I mean, the values that like() method reports are far far away from the one reported by the weather service.
When I measure ~26 ˚C, weather service says its ~21 ˚C 😕

**Comment by strikeentco** [comment]
Atmospheric pressure is not taken into account in calculating of real feel. Because atmospheric pressure is depends on the temperature.

Weather service which you are use, uses its own formulas and maybe several of formulas whose is presents here.

Formulas in this module is open and was invented by metheorologists and scientists from Australian Bureau of Meteorology, Meteorological Service of Canada, USA's National Weather Service etc.

But formulas from your weather service are private and cost a lot of money.

So yeah, they real feel may be different, like each formula gives different index :)
